### ISSUE TITLE
Build failure on GHC 9.10.3: join variable not in scope in src/Eval.hs

### ISSUE THREAD

**Issue by carmipao** [lucasscharenbroch/apl-interpreter#1]
The project fails to compile using GHC 9.10.3 and Cabal 3.12. The compiler reports that the function join is not in scope within src/Eval.hs. This appears to be a missing explicit import from Control.Monad.

```haskell
src/Eval.hs:99:21: error: [GHC-88464]
    Variable not in scope:
      join
        :: StateT IdMap IO (StateT IdMap IO Array) -> StateT IdMap IO Array
    Suggested fix:
      Add ‘join’ to the import list in the import of ‘Control.Monad’
      (at src/Eval.hs:5:1-27).
   |
99 | forkDDD f g h x y = join $ g <$> (f x y) <*> (h x y)
   |                     ^^^^
```

(Note: Similar errors occur at lines 102, 190, and 195)

Environment
    OS: Debian (Testing/Sid)
    GHC Version: 9.10.3
    Cabal Version: 3.12.1.0

Suggested Resolution
Adding an explicit import for join in src/Eval.hs resolves the issue.

```haskell
import Control.Monad (join, ...)
```
